// Integration: the stage-1 pipeline on a synthetic project, twice, with rendering disabled.
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, mkdirSync, writeFileSync, readFileSync, existsSync, readdirSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { execFileSync } from 'node:child_process';

const ARCH = new URL('../skills/architecture/scripts/arch/arch.mjs', import.meta.url).pathname;

function project() {
  const root = mkdtempSync(join(tmpdir(), 'proj-'));
  const w = (p, c) => { mkdirSync(join(root, p, '..'), { recursive: true }); writeFileSync(join(root, p), c); };
  w('package.json', JSON.stringify({ name: 'e2e', type: 'module', bin: { e2e: 'src/cli/main.js' }, dependencies: { express: '^4', leftpad: '^1' } }));
  w('src/cli/main.js', "import { run } from '../core/run.js'; import { serve } from '../web/server.js'; import express from 'express'; run(); serve(express);");
  w('src/core/run.js', 'export const run = () => 1;');
  w('src/web/server.js', "import { run } from '../core/run.js'; export const serve = () => run(); const k = process.env.API_TOKEN;");
  w('src/core/back.js', "import { serve } from '../web/server.js'; export const x = serve;");
  w('.github/workflows/ci.yml', 'name: ci\non:\n  push:\njobs:\n  test:\n    runs-on: ubuntu-latest\n    steps:\n      - run: npm test\n');
  return root;
}

function snapshot(dir) {
  const out = {};
  for (const f of readdirSync(dir, { recursive: true })) { const p = join(dir, f); try { out[f] = readFileSync(p, 'utf8'); } catch {} }
  return out;
}

test('arch run --out writes only under the out dir, is deterministic, and emits gaps', { timeout: 240_000 }, () => {
  const root = project();
  const out = mkdtempSync(join(tmpdir(), 'out-'));
  const before = readdirSync(root).sort();
  execFileSync('node', [ARCH, 'run', root, '--out', out, '--no-render'], { stdio: 'pipe' });
  assert.deepEqual(readdirSync(root).sort(), before, 'source tree untouched');
  for (const f of ['reference/components.json', 'reference/components.md', 'reference/drift.md', 'reference/deps.md', 'reference/delivery.md', 'reference/env.md', 'reference/fitness.md', 'architecture/CHECKLIST.md', 'architecture/model/spec.c4', 'architecture/model/generated.c4', 'architecture/model/hand.c4', 'architecture/_run/gaps.json', 'architecture/_run/interview.md', 'architecture/_run/index.md']) assert.ok(existsSync(join(out, f)), `missing ${f}`);
  const first = snapshot(out);
  execFileSync('node', [ARCH, 'run', root, '--out', out, '--no-render'], { stdio: 'pipe' });
  assert.deepEqual(snapshot(out), first, 'byte-identical on rerun');
  const gaps = JSON.parse(readFileSync(join(out, 'architecture/_run/gaps.json'), 'utf8'));
  assert.ok(gaps.some(g => g.id.startsWith('import-cycle')), 'cycle gap');
  assert.ok(gaps.some(g => g.class === 'project' && /leftpad/.test(JSON.stringify(g))), 'unused dep is a project gap');
  assert.match(readFileSync(join(out, 'reference/deps.md'), 'utf8'), /^generated by arch/);
  assert.doesNotMatch(readFileSync(join(out, 'architecture/_run/index.md'), 'utf8'), /\.(c4|json)\b/, 'human index never lists sources');
});
