#!/usr/bin/env node
// arch — stage-1 kit entry. Deterministic, read-only on the source tree; writes only under docs/reference and docs/architecture/_run.
// Subcommands: classify | extract components | fold | drift | check | run
import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { join, resolve, dirname } from 'node:path';
import { execFileSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import { classify } from './classify.mjs';
import { fold, cycles } from './fold.mjs';
import { drift } from './drift.mjs';
import { check } from './check.mjs';

const here = dirname(fileURLToPath(import.meta.url));
const [cmd, ...rest] = process.argv.slice(2);
const root = resolve(rest.find(a => !a.startsWith('--')) ?? '.');
const out = join(root, 'docs', 'reference');
const runDir = join(root, 'docs', 'architecture', '_run');
const write = (p, s) => { mkdirSync(dirname(p), { recursive: true }); writeFileSync(p, s); };
const header = what => `generated by arch ${what} (kit ${JSON.parse(readFileSync(join(here, '..', '..', '..', '..', '..', 'package.json'), 'utf8')).version}) — do not hand-edit\n`;

function loadRules() {
  const p = join(root, 'docs', 'architecture', 'fold-rules.json');
  if (existsSync(p)) return JSON.parse(readFileSync(p, 'utf8'));
  return JSON.parse(readFileSync(join(here, 'fold-rules.default.json'), 'utf8'));
}

function extractComponents() {
  const rules = loadRules();
  const json = execFileSync('npx', ['--yes', '-p', 'dependency-cruiser@18', 'depcruise', '--no-config', '--output-type', 'json', ...(rules.tsConfig ? ['--ts-config'] : []), '--include-only', rules.include ?? '^(src|apps|packages|lib)', ...(rules.roots ?? ['.'])], { cwd: root, maxBuffer: 1 << 28 }).toString();
  const g = fold(JSON.parse(json), rules.rules);
  const result = { ...g, cycles: cycles(g) };
  write(join(out, 'components.json'), JSON.stringify(result, null, 1));
  return result;
}

switch (cmd) {
  case 'classify': console.log(JSON.stringify(classify(root), null, 1)); break;
  case 'extract': { if (rest[0] !== 'components') throw new Error('only `extract components` is implemented in this scaffold'); const g = extractComponents(); console.log(`${g.nodes.length} components, ${g.edges.length} edges, ${g.cycles.length} cycles`); break; }
  case 'drift': {
    const code = JSON.parse(readFileSync(join(out, 'components.json'), 'utf8'));
    const handPath = join(root, 'docs', 'architecture', 'model', 'hand.json');
    const hand = existsSync(handPath) ? JSON.parse(readFileSync(handPath, 'utf8')) : { nodes: code.nodes, edges: [] };
    const d = drift(hand, code, { internal: new Set(code.nodes.map(n => n.id)) });
    write(join(out, 'drift.json'), JSON.stringify(d, null, 1));
    console.log(`unexplained: ${d.unexplained}; in code not hand: ${d.edges.inCodeNotHand.length}`); break;
  }
  case 'check': {
    const r = check(join(root, 'docs'));
    write(join(out, 'fitness.json'), JSON.stringify(r, null, 1));
    for (const x of r.results) console.log(`${x.ok ? 'ok  ' : 'FAIL'} ${x.id}${x.detail.length ? ' — ' + x.detail.slice(0, 5).join(', ') : ''}`);
    process.exitCode = r.ok ? 0 : 1; break;
  }
  case 'run': {
    const k = classify(root); write(join(runDir, 'classify.json'), JSON.stringify(k, null, 1));
    const g = extractComponents();
    const gaps = [];
    if (k.ambiguous) gaps.push({ id: 'kind-ambiguous', class: 'human', detail: k.kinds });
    if (g.cycles.length) gaps.push({ id: 'import-cycles', class: 'human', detail: g.cycles });
    write(join(runDir, 'gaps.json'), JSON.stringify(gaps, null, 1));
    console.log(`kinds ${k.kinds.join('+')} · ${g.nodes.length} components · ${g.edges.length} edges · ${g.cycles.length} cycles · ${gaps.length} gaps`); break;
  }
  default: console.log('usage: arch <classify|extract components|drift|check|run> [root]'); process.exitCode = 2;
}
