// Build docs/architecture/_run/brief.md — the one file stage 2 reads before writing anything.
// Pure function; every input is already computed by `arch run` during stage 1, so this module
// never re-derives kit facts and never touches the filesystem. Reuses checklist.mjs's own tables
// (viewShape, requiredViews) and check.mjs's own rule descriptions (DEFAULT_RULES) instead of
// duplicating that logic here.
import { inferKind } from './model.mjs';
import { viewShape, requiredViews } from './checklist.mjs';
import { DEFAULT_RULES } from './check.mjs';

const RULE_WHAT = Object.fromEntries(DEFAULT_RULES.map(r => [r.id, r.description]));

const cell = v => String(v ?? '').replace(/\r?\n/g, ' ').replace(/\|/g, '\\|').slice(0, 220);
const table = (headers, rows) => (rows.length
  ? [`| ${headers.join(' | ')} |`, `|${headers.map(() => '---').join('|')}|`, ...rows.map(r => `| ${r.map(cell).join(' | ')} |`)].join('\n')
  : '_none_');

/** One line of guidance for a required-but-missing view: where it lives and what shape it needs,
 * or — for a generated/index target — that hand-writing it is wrong and where the real fix is. */
function viewRecipe(view) {
  const s = viewShape(view);
  if (!s.file) return `${view}: no fixed file shape recorded for this view; see house-style.md's required-view table.`;
  if (view === 'adrs') return "adrs -> a real decision belongs at `<source root>/docs/decisions/NNN-title.md` (Nygard shape), only when it is evidenced in code or an existing doc, then re-run `arch run`; `decisions/README.md` is a generated index — never hand-edit it.";
  if (view === 'deployment') return "deployment -> either add a `deployment { }` block to `architecture/model/hand.c4` (kinds: environment, zone, node, device; `instanceOf <system>.<component>`) plus `views { deployment view deployment { include * } }`, which `arch run` renders to `reference/views/deployment.png`; or write `architecture/deployment.md` with a mermaid fence (```mermaid) or <svg>.";
  if (/^reference\//.test(s.file)) return `${view} -> \`${s.file}\` is generated from extractor data, not hand-written; find the matching gap in section 7 (class kit or project) and fix the underlying signal or record it as accepted — never write under \`reference/\` directly.`;
  const shapeBits = [s.needsFence ? 'a mermaid fence (```mermaid) or <svg>' : null, s.needsTableColumns.length ? `a table with columns: ${s.needsTableColumns.join(', ')}` : null].filter(Boolean);
  const shape = shapeBits.length ? shapeBits.join(' plus ') : 'prose covering the question this view answers (house-style.md)';
  return `${view} -> write \`${s.file}\` with ${shape}.`;
}

const RULE_RECIPES = {
  'docs.checklist-complete': detail => detail.map(viewRecipe).join('\n'),
  'docs.size-cap': detail => detail.map(d => { const [p, n] = d.split(' '); return `split or cut \`${p}\` (${n} lines) — one current-truth file per topic, 400-line cap.`; }).join('\n'),
  'docs.no-blank-checklist': () => 'CHECKLIST.md is kit-generated; the kit itself produced a row with no status token. File it in `_run/kit-issues.md` — never hand-edit CHECKLIST.md.',
  'docs.reference-generated': detail => `add the missing \`generated by arch …\` header line to: ${detail.join(', ')}. Files under \`reference/\` are kit-owned — if the header is genuinely missing, this is a kit bug: file it in \`_run/kit-issues.md\`, do not hand-edit \`reference/\`.`,
  'naming.retired': detail => `remove the retired term(s) from: ${detail.join(', ')} (the list lives in \`fold-rules.json\`'s \`retired\` field).`,
  'docs.cited-paths-exist': detail => `fix or delete these citations — the path does not resolve against the project root, the docs root, or the citing file's own directory: ${detail.join('; ')}.`,
  'docs.cell-length': detail => `shorten the table cell on these lines to ≤ 220 characters, moving the rest to prose below the table: ${detail.join(', ')}.`,
  'docs.view-shape': detail => `add a mermaid fence (\`\`\`mermaid) or an <svg> to: ${detail.join(', ')} — loop.md, signals.md, secrets.md and every journeys/*.md must be diagram-first.`,
  'docs.source-sha': detail => `these generated files are missing \`source: <sha>\` in their first 5 lines: ${detail.join(', ')} — a kit bug; file it in \`_run/kit-issues.md\`, do not hand-edit \`reference/\`.`,
};

function recipeFor(rule) {
  const fn = RULE_RECIPES[rule.id];
  if (fn) return fn(rule.detail ?? []);
  return `offending: ${(rule.detail ?? []).join(', ') || 'see reference/fitness.json'}.`;
}

const COMPLETENESS_RECIPES = {
  'risks.row-schema': d => `fill every risks.md row's likelihood, impact, trigger, mitigation and owner cell; offending rows: ${d.join(', ') || 'see completeness.json'}.`,
  'risks.failing-rules': d => `name every failing/unenforced fitness rule id somewhere in risks.md; missing: ${d.join(', ')}.`,
  'risks.risky-deps': d => `name every dependency flagged unused or risk >= medium in deps.json somewhere in risks.md; missing: ${d.join(', ')}.`,
  'risks.reviewed': d => `add (or refresh) a \`reviewed: YYYY-MM-DD\` header line in risks.md, within 30 days of the run date.${d.length ? ` ${d.join(', ')}` : ''}`,
  'stakeholders.defaults': d => `add a row — or an explicit \`struck: <name> — reason\` line — for each default stakeholder (operator, future maintainer, coding agent, reviewing agent, reader, security reviewer, end user); missing: ${d.join(', ')}.`,
  'stakeholders.views-covered': d => `name every CHECKLIST view in at least one stakeholders.md row; missing: ${d.join(', ')}.`,
  'stakeholders.views-exist': d => `every view named in stakeholders.md's third column must exist as a file or a ✓/partial CHECKLIST row; missing: ${d.join(', ')}.`,
  'glossary.kinds': d => `add a glossary term for every element kind used in the model; missing: ${d.join(', ')}.`,
  'glossary.frequent-nouns': d => `add a glossary term for (or strike) every capitalised domain noun used 3+ times across written docs; missing: ${d.join(', ')}.`,
  'glossary.mapped': d => `every glossary row's last column must cite a path, an ADR, or a code symbol; missing citation: ${d.join(', ')}.`,
  'glossary.retired': d => `remove retired terms from glossary.md; found in: ${d.join(', ')}.`,
  'deps.why': d => `give every direct dependency a why and an exit plan (\"none, accepted\" counts); missing: ${d.join(', ')}.`,
  'deps.used': d => `every dependency needs a production import site, or an explicit \`unused: yes\`; missing a site: ${d.join(', ')}.`,
  'scenarios.minimum': d => `write more scenario files under \`architecture/scenarios/\` — ${d.join(', ') || 'below the minimum for this kind'}.`,
};

function completenessRecipe(id, detail) {
  const fn = COMPLETENESS_RECIPES[id];
  if (fn) return fn(detail ?? []);
  return `offending: ${(detail ?? []).join(', ') || 'see completeness.json'}.`;
}

function projectSection({ sys, kinds, components, rules }) {
  const kindsLine = `${(kinds.kinds ?? []).join(' + ') || 'unknown'}${kinds.ambiguous ? ' (ambiguous)' : ''}`;
  const rows = [...(components.nodes ?? [])]
    .sort((a, b) => (b.files ?? 0) - (a.files ?? 0) || a.id.localeCompare(b.id))
    .map(n => {
      const kind = rules.kinds?.[n.id] ?? inferKind(n.id);
      const desc = rules.descriptions?.[n.id] ?? '';
      const out = (components.edges ?? []).filter(e => e.from === n.id).length;
      const into = (components.edges ?? []).filter(e => e.to === n.id).length;
      return [n.id, kind, desc, n.files, `${out} out / ${into} in`];
    });
  const cycles = (components.cycles ?? []).map(c => `${c.a}<->${c.b} (${c.ab}/${c.ba})`);
  return [
    '## 1. What this project is', '',
    `system \`${sys.id}\` ("${sys.title}") · kind(s): ${kindsLine} · engine: \`${components.engine ?? 'builtin'}\``,
    `classification evidence: ${(kinds.evidence ?? []).join(', ') || 'none'}`, '',
    table(['component', 'kind', 'description', 'files', 'edges'], rows), '',
    cycles.length ? `Import cycles: ${cycles.join('; ')}.` : 'No import cycles.',
  ].join('\n');
}

function driftSection({ drift, baseline }) {
  const undeclared = drift.edges?.undeclared ?? [];
  const absent = drift.edges?.inHandNotCode ?? [];
  const fmt = e => `${e.from}->${e.to}`;
  return [
    '## 2. Drift summary', '',
    `unexplained: ${drift.unexplained ?? 0} (undeclared in hand.c4: ${undeclared.length}, claimed-but-absent in code: ${absent.length}) · baseline size: ${(baseline?.edges ?? []).length}`,
    undeclared.length ? `Undeclared (in code, not in hand.c4): ${undeclared.map(fmt).join(', ')}.` : '',
    absent.length ? `Claimed-but-absent (in hand.c4, not in code): ${absent.map(fmt).join(', ')}.` : '',
  ].filter(Boolean).join('\n');
}

function fitnessSection({ fitness }) {
  const failing = (fitness.results ?? []).filter(r => !r.ok);
  const lines = ['## 3. Failing fitness rules — fix recipes', ''];
  if (!failing.length) { lines.push('None — `arch check` is green.'); return lines.join('\n'); }
  for (const r of failing) lines.push(`### \`${r.id}\``, RULE_WHAT[r.id] ?? '', recipeFor(r), '');
  return lines.join('\n').trimEnd();
}

/**
 * `missing` (the register's file/dir does not exist yet — nothing to evaluate) and `fail` (the
 * file exists but a criterion is unmet) need different guidance: a missing file gets one grouped
 * "write it first" line instead of one fabricated-sounding recipe per criterion.
 */
function completenessSection({ completeness }) {
  const byFile = new Map();
  const judgement = [];
  for (const reg of completeness.registers ?? []) {
    for (const c of reg.criteria ?? []) {
      if (c.status !== 'fail' && c.status !== 'missing' && c.status !== 'agent') continue;
      if (c.status === 'agent') { judgement.push(`\`${reg.file}\`/\`${c.id}\``); continue; }
      const bucket = byFile.get(reg.file) ?? { missing: [], failing: [] };
      (c.status === 'missing' ? bucket.missing : bucket.failing).push(c);
      byFile.set(reg.file, bucket);
    }
  }
  const lines = ['## 4. Completeness failures — fix recipes', ''];
  if (!byFile.size) lines.push('None failing.');
  for (const [file, { missing, failing }] of byFile) {
    if (missing.length) lines.push(`### \`${file}\` — does not exist yet`, `Write it first (see section 5's \`where\` column) — every criterion below applies once it does: ${missing.map(c => `\`${c.id}\``).join(', ')}.`, '');
    for (const f of failing) lines.push(`### \`${file}\` · \`${f.id}\``, completenessRecipe(f.id, f.detail), '');
  }
  if (judgement.length) lines.push('', 'Left to reviewer judgement (check type `agent`, not a failure — no recipe applies):', judgement.join(', '));
  return lines.join('\n').trimEnd();
}

function checklistSection({ kinds }) {
  // overview.md is not a CHECKLIST view but the one written document the house style requires of
  // every archetype; listing it here is what makes stage 2 write it (stage 2 writes only what §5 lists).
  const overview = ['overview', 'architecture/overview.md', 'prose: what the system is, its parts and how they talk, in the operator\'s words; every claim evidenced by a reference/ file or marked GAP'];
  const rows = [overview, ...requiredViews(kinds.kinds ?? []).filter(r => r.required === '✓').map(({ view }) => {
    const s = viewShape(view);
    const shape = [s.needsFence ? 'diagram fence' : null, s.needsTableColumns.length ? `columns: ${s.needsTableColumns.join(', ')}` : null].filter(Boolean).join('; ') || 'prose';
    return [view, s.file ?? '(none)', shape];
  })];
  return ['## 5. Required views for this shape', '', table(['view', 'where', 'content shape'], rows)].join('\n');
}

function handSection({ handEdges, rules }) {
  const edges = (handEdges ?? []).map(e => `${e.from}->${e.to}${e.runtime ? ' (runtime)' : ''}`);
  const areas = Object.keys(rules.areas ?? {});
  return [
    '## 6. Seeded `hand.c4` edges', '',
    'Edit `architecture/model/hand.c4` once, before any written doc, to record every context edge and area membership implied by sections 1-2; tag runtime-only relationships (`-[runtime]->` or a `(runtime)` suffix) so drift skips them.',
    '',
    `Currently declared edges: ${edges.length ? edges.join(', ') : '(none)'}.`,
    `Area groups (fold-rules.json \`areas\`): ${areas.length ? areas.join(', ') : 'none configured — run \`arch classify . --help-fold-rules\` for the field shape'}.`,
  ].join('\n');
}

function gapsSection({ gaps }) {
  const lines = ['## 7. Gaps and questions', ''];
  for (const cls of ['kit', 'project', 'human']) {
    const list = (gaps ?? []).filter(g => g.class === cls);
    lines.push(`**${cls}** (${list.length}): ${list.length ? list.map(g => `\`${g.id}\``).join(', ') : 'none'}.`);
  }
  lines.push('', 'Kit-class gaps go in `_run/kit-issues.md` verbatim (do not patch the project); project-class gaps are called out in `_run/review.md`, never fixed there; human-class gaps are curated into `_run/interview.md`.');
  return lines.join('\n');
}

const COMMANDS_SECTION = [
  '## 8. Commands stage 2 may run', '',
  '- `arch run <root> --out <docsDir> --no-render --now <date>` — the fast revalidate (extraction is seconds on a repo this size; rendering is the slow part). At most twice per review.',
  '- `arch check <root> --out <docsDir>` — rules only, no extraction.',
  '- `arch guard verify <root> --out <docsDir>` — once.',
  '- `arch guard close <root> --out <docsDir>` — once, final.',
  '- one final `arch run <root> --out <docsDir> --now <date>` WITH rendering, at the very end, after close.',
  '- nothing else.', '',
  "Do not read the kit's source. If a rule is unclear after reading this brief, record it in `_run/kit-issues.md` and take the default.",
].join('\n');

const DEFAULTS = {
  sys: { id: 'system', title: 'system' },
  kinds: { kinds: [], evidence: [], ambiguous: false },
  components: { nodes: [], edges: [], cycles: [], engine: 'builtin' },
  rules: {},
  drift: { unexplained: 0, edges: { undeclared: [], inHandNotCode: [] } },
  baseline: { edges: [] },
  fitness: { ok: true, results: [] },
  completeness: { registers: [] },
  handEdges: [],
  gaps: [],
};

/** inputs: sys, kinds (classify() output), components (extractComponents() output), rules
 * (fold-rules.json), drift (drift() output), baseline (drift-baseline.json), fitness (check()
 * output), completeness (evaluate() output), handEdges (handEdgesFromC4() output), gaps
 * (buildGaps() output), sha (short git sha or null). Every field defaults so tests can supply
 * only the section they are exercising. */
export function briefMd(inputs = {}) {
  const merged = { ...DEFAULTS, ...inputs };
  const header = ['generated by arch run', `source: ${inputs.sha ?? 'unknown'}`, '', '# Stage-2 brief', '', "Read this file first and only — it is the only file stage 2 has to read before writing.", ''].join('\n');
  const sections = [
    projectSection(merged), driftSection(merged), fitnessSection(merged), completenessSection(merged),
    checklistSection(merged), handSection(merged), gapsSection(merged), COMMANDS_SECTION,
  ];
  return `${header}\n${sections.join('\n\n')}\n`;
}
