// Extract the ADR index: number, title, status, and supersede/amend links from every *.md under
// the conventional decision-log locations. Deterministic, read-only, no lib.
import { existsSync, readFileSync, readdirSync } from 'node:fs';
import { join } from 'node:path';

export const CANDIDATE_DIRS = ['docs/decisions', 'docs/adr', 'adr', 'docs/architecture/decisions'];

const STATUS_LINE_RE = /^\*{0,2}status\*{0,2}[: ]\s*(.*)$/i;
const SUPERSEDED_BY_RE = /superseded by ADR? ?(\d+)/gi;
const SUPERSEDES_RE = /supersedes (\d+)/gi;
const AMENDED_BY_RE = /amended by (\d+)/gi;

function frontmatterStatus(text) {
  const m = text.match(/^---\r?\n([\s\S]*?)\r?\n---/);
  if (!m) return null;
  const s = m[1].match(/^status:\s*(.+)$/mi);
  return s ? s[1].trim().replace(/^["']|["']$/g, '') : null;
}

function bodyStatus(text) {
  for (const line of text.split(/\r?\n/)) {
    const m = line.match(STATUS_LINE_RE);
    if (m && m[1].trim()) return m[1].trim();
  }
  return null;
}

function firstH1(text) {
  const m = text.match(/^#\s+(.+)$/m);
  return m ? m[1].trim() : null;
}

function leadingNumber(filename) {
  const m = filename.match(/^(\d+)/);
  return m ? parseInt(m[1], 10) : null;
}

function mentions(text, re) {
  const out = [];
  for (const m of text.matchAll(re)) out.push(parseInt(m[1], 10));
  return [...new Set(out)].sort((a, b) => a - b);
}

/** ADRs found under any of the conventional decision-log dirs that exist. */
export function extractAdrs(root) {
  const dirs = CANDIDATE_DIRS.filter(d => existsSync(join(root, d)));
  const adrs = [];
  for (const dir of dirs) {
    const abs = join(root, dir);
    const files = readdirSync(abs).filter(f => f.endsWith('.md') && f.toLowerCase() !== 'readme.md').sort();
    for (const file of files) {
      let text; try { text = readFileSync(join(abs, file), 'utf8'); } catch { continue; }
      adrs.push({
        file, dir,
        number: leadingNumber(file),
        title: firstH1(text) ?? file,
        status: frontmatterStatus(text) ?? bodyStatus(text) ?? 'unknown',
        supersededBy: mentions(text, SUPERSEDED_BY_RE),
        supersedes: mentions(text, SUPERSEDES_RE),
        amendedBy: mentions(text, AMENDED_BY_RE),
      });
    }
  }
  adrs.sort((a, b) => (a.number ?? Infinity) - (b.number ?? Infinity) || a.file.localeCompare(b.file));
  return { adrs, dirs };
}

const ROW_CAP = 60;
function table(headers, rows) {
  const shown = rows.slice(0, ROW_CAP);
  const lines = [`| ${headers.join(' | ')} |`, `| ${headers.map(() => '---').join(' | ')} |`];
  for (const r of shown) lines.push(`| ${r.map(c => String(c ?? '')).join(' | ')} |`);
  let out = lines.join('\n');
  if (rows.length > ROW_CAP) out += `\n\n… ${rows.length - ROW_CAP} more`;
  return out;
}

const adrLabel = a => `${a.number ?? '?'} ${a.title}`;
const adrLink = a => `[${adrLabel(a)}](${a.dir}/${a.file})`;

/** decisions/README.md: header, superseded/amended table, then every ADR grouped by status with counts. */
export function adrIndexMd(json) {
  const adrs = json.adrs ?? [];
  const byNumber = new Map(adrs.filter(a => a.number != null).map(a => [a.number, a]));
  const lines = ['generated by arch extract adrs — do not hand-edit', '', '# Decisions'];

  const replaced = adrs.filter(a => a.supersededBy.length || a.amendedBy.length);
  lines.push('', '## Superseded and amended — read the replacement', '');
  if (replaced.length) {
    const rows = replaced.map(a => [
      adrLabel(a),
      a.supersededBy.length ? a.supersededBy.map(n => byNumber.has(n) ? adrLink(byNumber.get(n)) : `ADR ${n}`).join(', ') : '—',
      a.amendedBy.length ? a.amendedBy.map(n => byNumber.has(n) ? adrLink(byNumber.get(n)) : `ADR ${n}`).join(', ') : '—',
    ]);
    lines.push(table(['ADR', 'superseded by', 'amended by'], rows));
  } else {
    lines.push('none.');
  }

  const byStatus = new Map();
  for (const a of adrs) { const k = a.status || 'unknown'; if (!byStatus.has(k)) byStatus.set(k, []); byStatus.get(k).push(a); }
  for (const status of [...byStatus.keys()].sort()) {
    const rows = byStatus.get(status);
    lines.push('', `## ${status} (${rows.length})`, '');
    for (const a of rows) lines.push(`- ${adrLink(a)}`);
  }

  lines.push('', `total: ${adrs.length}`);
  return lines.join('\n') + '\n';
}
