import { test } from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, mkdirSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { extractTerraform, terraformMarkdown, resourceCounts, blocksOf } from './extract-terraform.mjs';

function project(files) {
  const root = mkdtempSync(join(tmpdir(), 'tf-'));
  for (const [p, c] of Object.entries(files)) { mkdirSync(join(root, p, '..'), { recursive: true }); writeFileSync(join(root, p), c); }
  return root;
}

test('blocksOf finds a block\'s own closing brace, not the first nested one', () => {
  const text = 'resource "a" "b" {\n  tags = {\n    Name = "x"\n  }\n}\nresource "c" "d" {\n}\n';
  const found = blocksOf(text, /resource\s+"([^"]+)"\s+"([^"]+)"\s*\{/g);
  assert.equal(found.length, 2);
  assert.match(found[0].body, /tags = \{\n {4}Name = "x"\n {2}\}/);
});

test('module blocks with a source resolve to a from/to edge', () => {
  const root = project({ 'main.tf': 'module "net" {\n  source = "./modules/net"\n}\n' });
  const r = extractTerraform(root);
  assert.deepEqual(r.modules, [{ name: 'net', source: './modules/net', dir: 'root', callsFrom: 'main.tf' }]);
  assert.deepEqual(r.edges, [{ from: 'root', to: './modules/net' }]);
});

test('a module call from a non-root dir uses that dir, not "root"', () => {
  const root = project({ 'envs/prod/main.tf': 'module "net" {\n  source = "../../modules/net"\n}\n' });
  const r = extractTerraform(root);
  assert.deepEqual(r.modules[0].dir, 'envs/prod');
  assert.deepEqual(r.edges[0].from, 'envs/prod');
});

test('provider blocks and required_providers both populate providers, merged by name', () => {
  const root = project({
    'main.tf': 'provider "aws" {\n  region = "us-east-1"\n}\n\nterraform {\n  required_providers {\n    aws = {\n      source  = "hashicorp/aws"\n      version = "~> 5.0"\n    }\n  }\n}\n',
  });
  const r = extractTerraform(root);
  assert.deepEqual(r.providers, [{ name: 'aws', version: '~> 5.0' }]);
});

test('resource blocks are counted per type, one row per instance in the JSON', () => {
  const root = project({
    'main.tf': 'resource "aws_instance" "web" {\n  ami = "x"\n}\nresource "aws_instance" "db" {\n  ami = "y"\n}\nresource "aws_s3_bucket" "assets" {\n  bucket = "z"\n}\n',
  });
  const r = extractTerraform(root);
  assert.equal(r.resources.length, 3);
  assert.deepEqual(resourceCounts(r.resources), [{ type: 'aws_instance', count: 2 }, { type: 'aws_s3_bucket', count: 1 }]);
});

test('a resource block with a nested attribute block does not get truncated at the nested close', () => {
  const root = project({ 'main.tf': 'resource "aws_instance" "web" {\n  tags = {\n    Name = "web"\n  }\n}\n' });
  const r = extractTerraform(root);
  assert.deepEqual(r.resources, [{ type: 'aws_instance', name: 'web', file: 'main.tf' }]);
});

test('a module without a source attribute is still listed but contributes no edge', () => {
  const root = project({ 'main.tf': 'module "net" {\n  count = 1\n}\n' });
  const r = extractTerraform(root);
  assert.deepEqual(r.modules, [{ name: 'net', source: null, dir: 'root', callsFrom: 'main.tf' }]);
  assert.deepEqual(r.edges, []);
});

test('output is deterministic and sorted by dir then name / type then name then file', () => {
  const root = project({
    'main.tf': 'module "z" {\n  source = "./z"\n}\nmodule "a" {\n  source = "./a"\n}\n',
  });
  const r1 = extractTerraform(root);
  const r2 = extractTerraform(root);
  assert.deepEqual(r1, r2);
  assert.deepEqual(r1.modules.map(m => m.name), ['a', 'z']);
});

test('opts.ignore excludes a directory from the scan', () => {
  const root = project({
    'main.tf': 'module "net" {\n  source = "./net"\n}\n',
    'archive/old.tf': 'module "dead" {\n  source = "./dead"\n}\n',
  });
  const r = extractTerraform(root, { ignore: ['archive'] });
  assert.deepEqual(r.modules.map(m => m.name), ['net']);
});

test('no .tf files gives empty everything without throwing', () => {
  const root = project({ 'README.md': 'hi\n' });
  assert.deepEqual(extractTerraform(root), { modules: [], providers: [], resources: [], edges: [] });
});

test('terraformMarkdown starts with the generated-by header and is idempotent', () => {
  const root = project({ 'main.tf': 'module "net" {\n  source = "./net"\n}\nresource "aws_vpc" "main" {\n  cidr_block = "x"\n}\n' });
  const json = extractTerraform(root);
  const md = terraformMarkdown(json);
  assert.match(md, /^generated by arch extract terraform — do not hand-edit\n/);
  assert.equal(md, terraformMarkdown(json));
});

test('terraformMarkdown renders a mermaid flowchart naming the module names, plus module/provider/resource tables', () => {
  const root = project({
    'main.tf': 'module "network" {\n  source = "./modules/network"\n}\nmodule "app" {\n  source = "./modules/app"\n}\nresource "aws_vpc" "main" {\n  cidr_block = "x"\n}\n',
  });
  const md = terraformMarkdown(extractTerraform(root));
  assert.match(md, /```mermaid\nflowchart LR/);
  assert.match(md, /network/);
  assert.match(md, /app/);
  assert.match(md, /## Modules/);
  assert.match(md, /## Providers/);
  assert.match(md, /## Resources/);
  assert.match(md, /aws_vpc/);
});

test('terraformMarkdown with no module calls still renders a valid (empty) flowchart', () => {
  const md = terraformMarkdown({ modules: [], providers: [], resources: [], edges: [] });
  assert.match(md, /flowchart LR\n {2}%% no module calls found\n```/);
});
