import { test } from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, mkdirSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { extractAdrs, adrIndexMd } from './extract-adrs.mjs';

function project(files) {
  const root = mkdtempSync(join(tmpdir(), 'adrs-'));
  for (const [p, c] of Object.entries(files)) { mkdirSync(join(root, p, '..'), { recursive: true }); writeFileSync(join(root, p), c); }
  return root;
}

test('reads number from the leading digits, title from the first H1, status from a body line', () => {
  const root = project({ 'docs/decisions/001-use-widgets.md': '# Use widgets\n\nStatus: Accepted\n\nBecause reasons.\n' });
  const r = extractAdrs(root);
  assert.deepEqual(r.adrs, [{ file: '001-use-widgets.md', dir: 'docs/decisions', number: 1, title: 'Use widgets', status: 'Accepted', supersededBy: [], supersedes: [], amendedBy: [] }]);
});

test('a bolded status line is also matched', () => {
  const root = project({ 'docs/decisions/002-x.md': '# X\n\n**Status**: Proposed\n' });
  const r = extractAdrs(root);
  assert.equal(r.adrs[0].status, 'Proposed');
});

test('front-matter status wins over a body status line', () => {
  const root = project({ 'docs/decisions/003-x.md': '---\nstatus: Deprecated\n---\n\n# X\n\nStatus: Accepted\n' });
  const r = extractAdrs(root);
  assert.equal(r.adrs[0].status, 'Deprecated');
});

test('an ADR with no status line at all is "unknown"', () => {
  const root = project({ 'docs/decisions/004-x.md': '# X\n\nbody only.\n' });
  const r = extractAdrs(root);
  assert.equal(r.adrs[0].status, 'unknown');
});

test('supersededBy, supersedes, and amendedBy mentions are parsed and deduplicated', () => {
  const root = project({
    'docs/decisions/005-old.md': '# Old\n\nStatus: Superseded\n\nSuperseded by ADR 6. Superseded by ADR 6.\n',
    'docs/decisions/006-new.md': '# New\n\nStatus: Accepted\n\nSupersedes 5.\n',
    'docs/decisions/007-amend.md': '# Amend\n\nStatus: Accepted\n\nAmended by 8.\n',
  });
  const r = extractAdrs(root);
  const byFile = Object.fromEntries(r.adrs.map(a => [a.file, a]));
  assert.deepEqual(byFile['005-old.md'].supersededBy, [6]);
  assert.deepEqual(byFile['006-new.md'].supersedes, [5]);
  assert.deepEqual(byFile['007-amend.md'].amendedBy, [8]);
});

test('checks all four conventional dirs and merges results', () => {
  const root = project({
    'docs/decisions/001-a.md': '# A\n\nStatus: Accepted\n',
    'adr/002-b.md': '# B\n\nStatus: Accepted\n',
  });
  const r = extractAdrs(root);
  assert.deepEqual(r.dirs.sort(), ['adr', 'docs/decisions']);
  assert.deepEqual(r.adrs.map(a => a.file), ['001-a.md', '002-b.md']);
});

test('an existing decisions/README.md is not treated as an ADR', () => {
  const root = project({
    'docs/decisions/README.md': 'generated by arch extract adrs — do not hand-edit\n',
    'docs/decisions/001-a.md': '# A\n\nStatus: Accepted\n',
  });
  const r = extractAdrs(root);
  assert.deepEqual(r.adrs.map(a => a.file), ['001-a.md']);
});

test('no candidate dirs exist gives an empty result without throwing', () => {
  const root = project({ 'README.md': 'hi\n' });
  assert.deepEqual(extractAdrs(root), { adrs: [], dirs: [] });
});

test('output is sorted by ADR number', () => {
  const root = project({
    'docs/decisions/010-later.md': '# Later\n\nStatus: Accepted\n',
    'docs/decisions/002-earlier.md': '# Earlier\n\nStatus: Accepted\n',
  });
  const r = extractAdrs(root);
  assert.deepEqual(r.adrs.map(a => a.number), [2, 10]);
});

test('adrIndexMd starts with the generated-by header', () => {
  const md = adrIndexMd({ adrs: [] });
  assert.match(md, /^generated by arch extract adrs — do not hand-edit\n/);
});

test('adrIndexMd renders the superseded/amended table only for ADRs with a replacement, linking to it', () => {
  const root = project({
    'docs/decisions/001-old.md': '# Old\n\nStatus: Superseded\n\nSuperseded by ADR 2.\n',
    'docs/decisions/002-new.md': '# New\n\nStatus: Accepted\n',
  });
  const json = extractAdrs(root);
  const md = adrIndexMd(json);
  assert.match(md, /## Superseded and amended — read the replacement/);
  assert.match(md, /\[2 New\]\(docs\/decisions\/002-new\.md\)/);
});

test('adrIndexMd says "none." when nothing is superseded or amended', () => {
  const root = project({ 'docs/decisions/001-a.md': '# A\n\nStatus: Accepted\n' });
  const md = adrIndexMd(extractAdrs(root));
  assert.match(md, /## Superseded and amended — read the replacement\n\nnone\./);
});

test('adrIndexMd groups ADRs by status with counts and reports a total', () => {
  const root = project({
    'docs/decisions/001-a.md': '# A\n\nStatus: Accepted\n',
    'docs/decisions/002-b.md': '# B\n\nStatus: Accepted\n',
    'docs/decisions/003-c.md': '# C\n\nStatus: Proposed\n',
  });
  const md = adrIndexMd(extractAdrs(root));
  assert.match(md, /## Accepted \(2\)/);
  assert.match(md, /## Proposed \(1\)/);
  assert.match(md, /total: 3/);
});
