// Stage-2 guard: snapshot the kit-owned files before the review agent runs, verify they are untouched after,
// and flag interview questions that belong to the kit rather than to a person.
import { createHash } from 'node:crypto';
import { readFileSync, existsSync, readdirSync, statSync, writeFileSync } from 'node:fs';
import { join, relative } from 'node:path';

export const KIT_OWNED = ['reference', 'architecture/CHECKLIST.md', 'architecture/_run/gaps.json', 'architecture/_run/questions.md', 'architecture/model/generated.c4', 'architecture/model/spec.c4'];
const KIT_SHAPED = /\b(extractor|regex|walker|fold rules?|kit|dependency-cruiser|likec4|render(er|ing)?|arch (run|check|extract))\b/i;
// A stage-2 review that claims every rule is green while fitness.json disagrees is a false-green
// report — the loop must not take that claim at face value.
const FALSE_GREEN_RE = /all (\d+ )?rules (`ok`|ok|pass)/i;

function files(docsDir) {
  const out = [];
  for (const k of KIT_OWNED) {
    const p = join(docsDir, k);
    if (!existsSync(p)) continue;
    if (statSync(p).isDirectory()) { const stack = [p]; while (stack.length) { const d = stack.pop(); for (const f of readdirSync(d)) { const q = join(d, f); statSync(q).isDirectory() ? stack.push(q) : out.push(q); } } }
    else out.push(p);
  }
  return out.filter(p => !/[/\\]views[/\\]/.test(p)).sort(); // views are re-rendered by the agent's allowed render step
}

export function snapshot(docsDir) {
  const hashes = {};
  for (const p of files(docsDir)) hashes[relative(docsDir, p).split('\\').join('/')] = createHash('sha256').update(readFileSync(p)).digest('hex');
  return { hashes };
}

/** fitness: parsed fitness.json ({ ok, results }), when the caller wants the false-green check too. */
export function verify(docsDir, snap, { fitness } = {}) {
  const now = snapshot(docsDir).hashes;
  const modified = Object.keys(snap.hashes).filter(k => now[k] !== undefined && now[k] !== snap.hashes[k]).sort();
  const deleted = Object.keys(snap.hashes).filter(k => now[k] === undefined).sort();
  const added = Object.keys(now).filter(k => snap.hashes[k] === undefined).sort();
  const fileGuardOk = modified.length === 0 && deleted.length === 0 && added.length === 0;
  const reasons = [];
  const reviewPath = join(docsDir, 'architecture', '_run', 'review.md');
  if (fitness?.ok === false && existsSync(reviewPath) && FALSE_GREEN_RE.test(readFileSync(reviewPath, 'utf8'))) {
    reasons.push('review claims green while fitness has failing rules');
  }
  return { ok: fileGuardOk && reasons.length === 0, modified, deleted, added, reasons };
}

/** Questions in interview.md whose title reads as a kit concern (extractor, regex, renderer) rather than an operator decision. */
export function kitShapedQuestions(interviewMd) {
  return interviewMd.split(/\r?\n/).filter(l => /^###\s+Q\d+/.test(l)).filter(l => KIT_SHAPED.test(l)).map(l => l.replace(/^###\s+/, '').trim());
}

export function guardReport(docsDir, snap, { fitness } = {}) {
  const v = verify(docsDir, snap, { fitness });
  const ip = join(docsDir, 'architecture', '_run', 'interview.md');
  const kitQ = existsSync(ip) ? kitShapedQuestions(readFileSync(ip, 'utf8')) : [];
  const lines = ['generated by arch guard verify', '', `kit-owned files untouched: ${v.ok ? 'yes' : 'NO'}`];
  for (const [k, list] of Object.entries({ modified: v.modified, deleted: v.deleted, added: v.added })) if (list.length) lines.push(`${k}: ${list.join(', ')}`);
  for (const r of v.reasons ?? []) lines.push(`reason: ${r}`);
  lines.push(`kit-shaped interview questions: ${kitQ.length}`); for (const q of kitQ) lines.push(`- ${q}`);
  return { ok: v.ok && kitQ.length === 0, text: lines.join('\n') + '\n', verify: v, kitShaped: kitQ };
}

export function writeSnapshot(docsDir) {
  const p = join(docsDir, 'architecture', '_run', '.stage2-guard.json');
  writeFileSync(p, JSON.stringify({ ...snapshot(docsDir), pid: process.pid, at: new Date().toISOString() }, null, 1) + '\n');
  return p;
}
/** A kit run during stage 2 legitimately rewrites kit-owned files; re-hash them so verify measures the
 * agent's edits since the LAST kit run, not since the review opened. The opening stamp is kept. */
export function refreshSnapshot(docsDir) {
  const prev = readSnapshot(docsDir);
  const p = join(docsDir, 'architecture', '_run', '.stage2-guard.json');
  writeFileSync(p, JSON.stringify({ ...snapshot(docsDir), pid: prev.pid, at: prev.at, refreshedAt: new Date().toISOString() }, null, 1) + '\n');
  return p;
}
export function readSnapshot(docsDir) { const p = join(docsDir, 'architecture', '_run', '.stage2-guard.json'); if (!existsSync(p)) throw new Error('no stage-2 snapshot; run `arch guard snapshot` before the review'); return JSON.parse(readFileSync(p, 'utf8')); }

/** True while a stage-2 review is in progress: the pre-review snapshot exists and stage 2 has not been closed. */
export function isOpen(docsDir) {
  const snapPath = join(docsDir, 'architecture', '_run', '.stage2-guard.json');
  const donePath = join(docsDir, 'architecture', '_run', '.stage2-done');
  return existsSync(snapPath) && !existsSync(donePath);
}

/** Marks stage 2 finished: writes the .stage2-done marker isOpen checks for. When `snap` is given the
 * same check `guard verify` runs is applied first, so close and verify can never disagree: a tampered
 * tree gets `{ ok: false, path: null, report }` and no marker. */
export function close(docsDir, { snap, fitness } = {}) {
  const report = snap ? guardReport(docsDir, snap, { fitness }) : null;
  if (report && !report.ok) return { ok: false, path: null, report };
  const p = join(docsDir, 'architecture', '_run', '.stage2-done');
  writeFileSync(p, JSON.stringify({ at: new Date().toISOString() }, null, 1) + '\n');
  return { ok: true, path: p, report };
}
