import { test } from 'node:test';
import assert from 'node:assert/strict';
import { toMarkdown, table } from './markdown.mjs';

test('table renders a GFM table and caps at 60 rows with a trailing "... N more"', () => {
  const t = table(['a', 'b'], [['1', '2']]);
  assert.equal(t, '| a | b |\n| --- | --- |\n| 1 | 2 |');
  const many = table(['a'], Array.from({ length: 65 }, (_, i) => [String(i)]));
  const lines = many.split('\n');
  assert.equal(lines.filter(l => l.startsWith('| ')).length, 62); // header + separator + 60 rows
  assert.ok(many.endsWith('… 5 more'));
});

test('toMarkdown throws on an unknown kind', () => {
  assert.throws(() => toMarkdown('nope', {}), /unknown kind/);
});

test('deps: generated header names the command; unused deps sort before used ones', () => {
  const json = { deps: [
    { name: 'zod', version: '^3.0.0', usedBy: ['app'], importSites: ['src/a.ts'], why: 'imported by src/a.ts', unused: false },
    { name: 'leftpad', version: '^1.0.0', usedBy: ['app'], importSites: [], why: null, unused: true },
  ], lockfile: 'package-lock.json', notes: [] };
  const md = toMarkdown('deps', json);
  assert.ok(md.startsWith('generated by arch extract deps — do not hand-edit\n'));
  assert.ok(md.includes('# Dependencies'));
  const lIdx = md.indexOf('leftpad'), zIdx = md.indexOf('zod');
  assert.ok(lIdx > 0 && zIdx > 0 && lIdx < zIdx);
  assert.ok(md.includes('lockfile: package-lock.json'));
});

test('delivery: jobs with an unmet need sort before clean jobs', () => {
  const json = { workflows: [{ file: '.github/workflows/ci.yml', name: 'CI', triggers: ['push'], jobs: [
    { id: 'build', needs: [], runsOn: 'ubuntu-latest', steps: [{ uses: 'actions/checkout@v4' }] },
    { id: 'test', needs: ['missing'], runsOn: 'ubuntu-latest', steps: [] },
  ] }], requiredChecks: null, notes: [] };
  const md = toMarkdown('delivery', json, { command: 'extract delivery' });
  const testIdx = md.indexOf('| .github/workflows/ci.yml | test'), buildIdx = md.indexOf('| .github/workflows/ci.yml | build');
  assert.ok(testIdx > 0 && buildIdx > 0 && testIdx < buildIdx);
});

test('ext-points: empty registries sort first', () => {
  const json = { points: [
    { name: 'skill', glob: 'skills/*/SKILL.md', count: 3, installed: ['a', 'b', 'c'] },
    { name: 'adapters', glob: '**/adapters/*', count: 0, installed: [] },
  ] };
  const md = toMarkdown('ext-points', json);
  assert.ok(md.indexOf('adapters') < md.indexOf('skill'));
});

test('api: openapi source renders a single-row summary table', () => {
  const md = toMarkdown('api', { source: 'openapi', file: 'openapi.yaml', pathCount: 12 });
  assert.ok(md.includes('| openapi.yaml | 12 |'));
});

test('api: literal source renders groups, byOwner, and a path count line', () => {
  const json = { source: 'literals', paths: ['/api/users'], groups: [{ group: 'users', count: 1 }], byOwner: [{ dir: 'packages/library', count: 1 }], notes: [] };
  const md = toMarkdown('api', json);
  assert.ok(md.includes('packages/library'));
  assert.ok(md.includes('1 distinct literal path(s)'));
});

test('tests: untagged seams sort before tagged ones; tagging-adopted line present', () => {
  const json = { total: 2, byDir: [{ dir: 'packages/flows', count: 2 }], tagged: { seams: [
    { seam: 'auth', layers: { unit: 1, contract: 0, journey: 0, ground: 0 } },
    { seam: 'billing', layers: { unit: 0, contract: 0, journey: 0, ground: 0 } },
  ], count: 2 }, taggingAdopted: true };
  const md = toMarkdown('tests', json);
  assert.ok(md.indexOf('billing') < md.indexOf('auth'));
  assert.ok(md.includes('tagging adopted: yes'));
});

test('env: secret-like vars sort first', () => {
  const json = { vars: [{ name: 'PORT', count: 3, sites: ['a.ts:1'] }, { name: 'API_SECRET', count: 1, sites: ['b.ts:1'] }], secretLike: ['API_SECRET'] };
  const md = toMarkdown('env', json);
  assert.ok(md.indexOf('API_SECRET') < md.indexOf('PORT'));
});

test('ui: renders routes and a data-attribute summary line', () => {
  const json = { routes: [{ route: '/health', file: 'src/server.ts' }], dataAttributes: { count: 1, names: ['data-testid'] } };
  const md = toMarkdown('ui', json);
  assert.ok(md.includes('/health'));
  assert.ok(md.includes('1 distinct data-* attribute(s): data-testid'));
});

test('components: cycles sort before the component table', () => {
  const json = { nodes: [{ id: 'flows', files: 3, tests: 1 }], edges: [], cycles: [{ a: 'agents', b: 'flows', ab: 2, ba: 1 }] };
  const md = toMarkdown('components', json);
  assert.ok(md.indexOf('agents') < md.indexOf('| flows | 3 | 1 |'));
});

test('drift: verdict line reflects unexplained count', () => {
  const clean = toMarkdown('drift', { nodes: { added: [], removed: [], renamed: [] }, edges: { inHandNotCode: [], inCodeNotHand: [], skippedRuntime: 0 }, unexplained: 0 });
  assert.ok(clean.includes('verdict: clean'));
  const dirty = toMarkdown('drift', { nodes: { added: ['x'], removed: [], renamed: [] }, edges: { inHandNotCode: [{ from: 'a', to: 'b' }], inCodeNotHand: [], skippedRuntime: 0 }, unexplained: 1 });
  assert.ok(dirty.includes('verdict: 1 unexplained edge(s)'));
});

test('fitness: failing rules sort before passing ones', () => {
  const json = { ok: false, results: [{ id: 'a', ok: true, detail: [] }, { id: 'b', ok: false, detail: ['x'] }] };
  const md = toMarkdown('fitness', json);
  assert.ok(md.indexOf('| b |') < md.indexOf('| a |'));
});

test('jobs: scheduled rows sort before unscheduled ones and the header names the extract command', () => {
  const json = { jobs: [
    { source: 'make', id: 'build', file: 'Makefile', schedule: null, command: 'build' },
    { source: 'k8s-cronjob', id: 'cleanup', file: 'deploy/cleanup.yaml', schedule: '0 3 * * *', command: null },
  ], notes: [] };
  const md = toMarkdown('jobs', json);
  assert.ok(md.startsWith('generated by arch extract jobs — do not hand-edit\n'));
  assert.ok(md.includes('# Jobs'));
  const rows = md.split('\n').filter(l => /^\| (make|k8s-cronjob) /.test(l));
  assert.match(rows[0], /^\| k8s-cronjob \| deploy\/cleanup\.yaml \| cleanup \| 0 3 \* \* \* \|/);
  assert.match(rows[1], /^\| make \| Makefile \| build \|  \| build \|/);
});
