// Build docs/architecture/_run/index.md — the human-facing bundle. Rendered views first, then
// written docs, then generated markdown, then interview + review. Never lists .c4 or .json: any
// such path slipped in by a caller is filtered out here as a safety net.
const VIEWS_REL = '../../reference/views/';
const isMd = p => /\.md$/i.test(p);

// Fallback captions for the house views, used only when the caller has no view titles of its own
// (e.g. parsed from hand.c4 / model.json) to pass in as `titles`.
const CAPTIONS = { index: 'System context — who and what surrounds the system', containers: 'Containers — the main runtime parts and how they talk', components: 'Components — production imports between parts (minor edges omitted)', deployment: 'Deployment — where the parts run' };
function captionFor(pngName, titles) {
  const base = pngName.replace(/\.png$/i, '');
  if (titles[base]) return titles[base];
  if (CAPTIONS[base]) return CAPTIONS[base];
  const words = base.split(/[-_]+/).filter(Boolean).map(w => w[0].toUpperCase() + w.slice(1)).join(' ');
  return `Scenario — ${words}`;
}

function bulletList(paths) {
  return paths.filter(isMd).map(p => `- [${p.split('/').pop()}](${p})`).join('\n');
}

/**
 * `titles`: optional {viewId: title} map — the caller's own view titles (e.g. parsed from the
 * `title`/`description` lines of hand.c4 or from reference/components.json's view metadata),
 * keyed by the view id (the PNG basename without extension). Falls back to the built-in CAPTIONS
 * map, then to a title-cased guess from the filename, exactly as before when no titles are given.
 */
export function indexMd({ views = [], written = [], generated = [], interviewPath, reviewPath, titles = {} } = {}) {
  const sections = ['# Architecture bundle', '', 'generated by arch present — do not hand-edit', ''];

  sections.push('## Views', '');
  for (const v of views) {
    sections.push(`![${captionFor(v, titles)}](${VIEWS_REL}${v})`, `*${captionFor(v, titles)}*`, '');
  }
  if (!views.length) sections.push('_no rendered views_', '');

  sections.push('## Written docs', '');
  sections.push(written.filter(isMd).length ? bulletList(written) : '_none_', '');

  sections.push('## Generated docs', '');
  sections.push(generated.filter(isMd).length ? bulletList(generated) : '_none_', '');

  sections.push('## Interview', '');
  sections.push(interviewPath && isMd(interviewPath) ? `- [interview](${interviewPath})` : '_no open questions_', '');

  sections.push('## Review', '');
  sections.push(reviewPath && isMd(reviewPath) ? `- [review](${reviewPath})` : '_no review on file_', '');

  return `${sections.join('\n').replace(/\n{3,}/g, '\n\n').trimEnd()}\n`;
}
