// Build docs/architecture/_run/index.md — the human-facing bundle. Rendered views first, then
// written docs, then generated markdown, then interview + review. Never lists .c4 or .json: any
// such path slipped in by a caller is filtered out here as a safety net.
const VIEWS_REL = '../../reference/views/';
const isMd = p => /\.md$/i.test(p);

function captionFor(pngName) {
  const base = pngName.replace(/\.png$/i, '');
  return base.split(/[-_]+/).filter(Boolean).map(w => w[0].toUpperCase() + w.slice(1)).join(' ');
}

function bulletList(paths) {
  return paths.filter(isMd).map(p => `- [${p.split('/').pop()}](${p})`).join('\n');
}

export function indexMd({ views = [], written = [], generated = [], interviewPath, reviewPath } = {}) {
  const sections = ['# Architecture bundle', '', 'generated by arch present — do not hand-edit', ''];

  sections.push('## Views', '');
  for (const v of views) {
    sections.push(`![${captionFor(v)}](${VIEWS_REL}${v})`, `*${captionFor(v)}*`, '');
  }
  if (!views.length) sections.push('_no rendered views_', '');

  sections.push('## Written docs', '');
  sections.push(written.filter(isMd).length ? bulletList(written) : '_none_', '');

  sections.push('## Generated docs', '');
  sections.push(generated.filter(isMd).length ? bulletList(generated) : '_none_', '');

  sections.push('## Interview', '');
  sections.push(interviewPath && isMd(interviewPath) ? `- [interview](${interviewPath})` : '_no open questions_', '');

  sections.push('## Review', '');
  sections.push(reviewPath && isMd(reviewPath) ? `- [review](${reviewPath})` : '_no review on file_', '');

  return `${sections.join('\n').replace(/\n{3,}/g, '\n\n').trimEnd()}\n`;
}
