import { test } from 'node:test';
import assert from 'node:assert/strict';
import { indexMd } from './present.mjs';

test('renders views first as image links; known views get house captions, others read as scenarios', () => {
  const md = indexMd({ views: ['index.png', 'pr-path.png'] });
  assert.match(md, /## Views/);
  assert.match(md, /!\[System context[^\]]*\]\(\.\.\/\.\.\/reference\/views\/index\.png\)/);
  assert.match(md, /\*System context/);
  assert.match(md, /!\[Scenario — Pr Path\]\(\.\.\/\.\.\/reference\/views\/pr-path\.png\)/);
});

test('lists written docs, then generated docs, then interview and review, in that order', () => {
  const md = indexMd({
    views: ['a.png'],
    written: ['docs/architecture/overview.md', 'docs/architecture/risks.md'],
    generated: ['docs/reference/deps.md'],
    interviewPath: 'docs/architecture/_run/interview.md',
    reviewPath: 'docs/architecture/_run/review.md',
  });
  const order = ['## Views', '## Written docs', '## Generated docs', '## Interview', '## Review'].map(h => md.indexOf(h));
  assert.deepEqual(order, [...order].sort((a, b) => a - b));
  assert.match(md, /\[overview\.md\]\(docs\/architecture\/overview\.md\)/);
  assert.match(md, /\[deps\.md\]\(docs\/reference\/deps\.md\)/);
  assert.match(md, /\[interview\]\(docs\/architecture\/_run\/interview\.md\)/);
  assert.match(md, /\[review\]\(docs\/architecture\/_run\/review\.md\)/);
});

test('never lists .c4 or .json paths even if the caller passes them', () => {
  const md = indexMd({
    written: ['docs/architecture/model/hand.c4', 'docs/architecture/overview.md'],
    generated: ['docs/reference/components.json', 'docs/reference/deps.md'],
  });
  assert.ok(!md.includes('.c4'));
  assert.ok(!md.includes('components.json'));
  assert.match(md, /overview\.md/);
  assert.match(md, /deps\.md/);
});

test('empty inputs render placeholder text, never a blank section', () => {
  const md = indexMd({});
  assert.match(md, /_no rendered views_/);
  assert.match(md, /_none_/);
  assert.match(md, /_no open questions_/);
  assert.match(md, /_no review on file_/);
});

test('carries a generated-by header and never hand-edited note', () => {
  const md = indexMd({});
  assert.match(md, /^# Architecture bundle\n\ngenerated by arch present/);
});
